import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Header from "@/components/layouts/header";
import { PagesProgressBar as ProgressBar } from "next-nprogress-bar";
import Providers from "@/components/layouts/ProgressBarProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "h-screen grid grid-cols-5"}>
        <Sidebar />
        <main className="lg:col-span-4 col-span-5 bg-black/10 h-screen overflow-y-auto flex flex-col">
          <Header />
          <div className="p-4 overflow-y-auto">{children}</div>
          <Providers></Providers>
          <Toaster position="top-right" reverseOrder={true} />
        </main>
      </body>
    </html>
  );
}
